name: Build and Push Docker Image to AWS ECR

on:
  push:
    branches:
      - main
      - dev  # Trigger on commits to main and dev branches

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up AWS CLI
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    # Log in to ECR
    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    # Build Docker image
    - name: Build Docker image
      run: |
        docker build -t bar-task:${{ github.sha }} ./app-python

    # Tag Docker image
    - name: Tag Docker image
      run: |
        SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
        BRANCH_NAME=$(echo "${{ github.ref_name }}" | sed 's|refs/heads/||')
        REPOSITORY=${{ steps.login-ecr.outputs.registry }}/bar-task
        docker tag bar-task:${{ github.sha }} $REPOSITORY:latest
        docker tag bar-task:${{ github.sha }} $REPOSITORY:${BRANCH_NAME}-${SHORT_SHA}

    # Push Docker image to ECR
    - name: Push Docker image to ECR
      run: |
        SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
        BRANCH_NAME=$(echo "${{ github.ref_name }}" | sed 's|refs/heads/||')
        REPOSITORY=${{ steps.login-ecr.outputs.registry }}/bar-task
        docker push $REPOSITORY:latest
        docker push $REPOSITORY:${BRANCH_NAME}-${SHORT_SHA}
