name: Build and Push Docker Image to AWS ECR

on:
  push:
    branches:
      - main
      - dev  # Trigger on commits to main and dev branches
      - V2

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up AWS CLI
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    # Log in to ECR
    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    # Build Docker image
    - name: Build Docker image
      run: |
        docker build -t whist-app:${{ github.sha }} ./app-python

    # Tag Docker image
    - name: Tag Docker image
      run: |
        IMAGE_TAG=whist-app:${{ github.sha }}
        docker tag $IMAGE_TAG ${{ steps.login-ecr.outputs.registry }}/whist-app-repository:latest
        docker tag $IMAGE_TAG ${{ steps.login-ecr.outputs.registry }}/whist-app-repository:${{ github.event.repository.default_branch }}-${{ github.sha::7 }}

    # Push Docker image to ECR
    - name: Push Docker image to ECR
      run: |
        docker push ${{ steps.login-ecr.outputs.registry }}/whist-app-repository:latest
        docker push ${{ steps.login-ecr.outputs.registry }}/whist-app-repository:${{ github.event.repository.default_branch }}-${{ github.sha::7 }}
